# Alacritty TOML Configuration
# version: 14.0.0

# FONTS
##################################
[font]
size = 12.0

# JETBRAINS
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

# GENERAL
######################
[general]
# Live config reload (changes require restart)
live_config_reload = true

# SELECTION
######################
[selection]
# When set to true, selected text will be copied to the primary clipboard.
# Default: false
save_to_clipboard = false

# CURSOR
######################
[cursor]
style = { shape = "Block", blinking = "Off" }

# MOUSE
######################
[mouse]
# When this is true, the cursor is temporarily hidden when typing.
# Default: false
hide_when_typing = false

# SCROLLING
######################
[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying 0 will disable scrolling.
# Limited to 100000.
history = 10000

# WINDOW
######################
[window]
# Window dimensions (changes require restart)
# "Fullscreen" | "Maximized"
startup_mode = "Maximized"
opacity = 0.90
option_as_alt = "Both"
